server:
  port: 8080
  servlet:
    context-path: "/ho-api"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wocao123.
    url: jdbc:mysql://39.102.73.157:3306/hotel?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
mybatis:
  type-aliases-package: classpath*:cn.edu.hotel.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml

